apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ include "dbs-payment-order-integration-service.name" . }}"
  labels:
{{ include "dbs-payment-order-integration-service.labels" . | indent 4 }}
data:
  {{- if .Values.secrets.AMQU }}
  AMQU: {{ .Values.secrets.AMQU | b64enc | quote }}
  {{- else }}
  AMQU: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.AMQP }}
  AMQP: {{ .Values.secrets.AMQP | b64enc | quote }}
  {{- else }}
  AMQP: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.JAVA_TOOL_OPTIONS }}
  JAVA_TOOL_OPTIONS: {{ .Values.secrets.JAVA_TOOL_OPTIONS | b64enc | quote }}
  {{- else }}
  JAVA_TOOL_OPTIONS: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.LOADER_PATH }}
  LOADER_PATH: {{ .Values.secrets.LOADER_PATH | b64enc | quote }}
  {{- else }}
  LOADER_PATH: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.AWS_REGION }}
  AWS_REGION: {{ .Values.secrets.AWS_REGION | b64enc | quote }}
  {{- else }}
  AWS_REGION: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.SIG_SECRET_KEY }}
  SIG_SECRET_KEY: {{ .Values.secrets.SIG_SECRET_KEY | b64enc | quote }}
  {{- else }}
  SIG_SECRET_KEY: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.EXTERNAL_SIG_SECRET_KEY }}
  EXTERNAL_SIG_SECRET_KEY: {{ .Values.secrets.EXTERNAL_SIG_SECRET_KEY | b64enc | quote }}
  {{- else }}
  EXTERNAL_SIG_SECRET_KEY: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.EXTERNAL_ENC_SECRET_KEY }}
  EXTERNAL_ENC_SECRET_KEY: {{ .Values.secrets.EXTERNAL_ENC_SECRET_KEY | b64enc | quote }}
  {{- else }}
  EXTERNAL_ENC_SECRET_KEY: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.USERCTX_KEY }}
  USERCTX_KEY: {{ .Values.secrets.USERCTX_KEY | b64enc | quote }}
  {{- else }}
  USERCTX_KEY: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.RDSURL }}
  RDSURL: {{ .Values.secrets.RDSURL | b64enc | quote }}
  {{- else }}
  RDSURL: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.DBU }}
  DBU: {{ .Values.secrets.DBU | b64enc | quote }}
  {{- else }}
  DBU: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.DBP }}
  DBP: {{ .Values.secrets.DBP | b64enc | quote }}
  {{- else }}
  DBP: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.IDENTITY_USERNAME }}
  IDENTITY_USERNAME: {{ .Values.secrets.IDENTITY_USERNAME | b64enc | quote }}
  {{- else }}
  IDENTITY_USERNAME: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.IDENTITY_PASSWORD }}
  IDENTITY_PASSWORD: {{ .Values.secrets.IDENTITY_PASSWORD | b64enc | quote }}
  {{- else }}
  IDENTITY_PASSWORD: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.MULESOFT_API_KEYS }}
  MULESOFT_API_KEYS: {{ .Values.secrets.MULESOFT_API_KEYS | b64enc | quote }}
  {{- else }}
  MULESOFT_API_KEYS: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.BB_CLIENT_SECRET_ID }}
  BB_CLIENT_SECRET_ID: {{ .Values.secrets.BB_CLIENT_SECRET_ID | b64enc | quote }}
  {{- else }}
  BB_CLIENT_SECRET_ID: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}  