server:
  port: 9915

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
      enabled: false

rejectRecurringStartingToday:
  enabled: false
  message: The start date cannot be today's date. Please choose a future date.

transferToContact:
  externalArrangementIdFormat: "%s-S-00"
  leftPadAccountNumber: true
  leftPadLength: 10
  leftPadChar: "0"

finite:
  hosturl: http://localhost:9090
  apikey: demo-api-key-do-not-use-in-production
  paymentFrequencies:
    -
      backbase: ONCE
      finite: SINGLE_PAY
    -
      backbase: DAILY
      finite: DAILY
    -
      backbase: WEEKLY
      finite: WEEKLY
    -
      backbase: BIWEEKLY
      finite: BIWEEKLY
    -
      backbase: MONTHLY
      finite: MONTHLY
    -
      backbase: QUARTERLY
      finite: QUARTERLY
    -
      backbase: YEARLY
      finite: ANNUALLY

logging:
  level:
    net.trexis.experts: WARN

timeZone:
  zoneId: America/Denver